name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform Configuration
        run: terraform apply -auto-approve

      - name: Verify S3 Bucket
        run: aws --endpoint-url=http://localhost:4566 s3 ls s3://my-test-bucket

      - name: Clean up
        run: terraform destroy -auto-approve
